
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/shimizu?useSSL=false&characterEncoding=utf-8&serverTimezone=GMT%2b8
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

