
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false&characterEncoding=utf-8&serverTimezone=GMT%2b8
  jpa:
    hibernate:
      ddl-auto: update
#    database-platform: org.hibernate.dialect.MySQLDialect 这条是错的
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  port: 8010
  servlet:
    context-path: /shimizu
