spring:
  profiles:
    active: dev
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/shimizu?useSSL=false&characterEncoding=utf-8&serverTimezone=GMT%2b8
  jpa:
    hibernate:
      ddl-auto: update
    #    database-platform: org.hibernate.dialect.MySQLDialect 这条是错的
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    host: 127.0.0.1:3306
    port: 6379
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000
    database: 0
    password:
#  security:
#    user:
#      name: user
#      password: user
#      roles: user,admin
server:
  port: 8011
#  servlet:
#    context-path: /shimizu
district:
  district-name: 温州市
  district-number: 3303
time-conf:
  duration: 3d
districts:
  job: true
  district-name: 温州市
  district-number: 3303
static-conf:
  name: 张三
  flag: true